# Generated by Django 5.1.1 on 2024-10-03 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_badge_article_tag_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
