# Generated by Django 5.1.1 on 2024-10-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_badge_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
