# Generated by Django 5.1.1 on 2024-10-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_article_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scopes',
            field=models.ManyToManyField(to='articles.badge', verbose_name='Тег'),
        ),
    ]
