# Generated by Django 5.1.1 on 2024-10-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_scopes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='tag',
            new_name='scopes',
        ),
        migrations.RemoveField(
            model_name='article',
            name='scopes',
        ),
    ]
