# Generated by Django 5.1.1 on 2024-10-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_rename_scopes_scope_scope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Раздел'},
        ),
    ]
