<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-09-25 03:46
=======
# Generated by Django 5.1.1 on 2024-09-23 12:48
>>>>>>> ec3b3c7556d62297291a04404e9dc6951832d0d7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_group_alter_student_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(to='school.teacher'),
        ),
    ]
